//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.12 at 10:02:46 PM CEST 
//


package se.sie.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Typdefinition för en referens till en verifikationspost
 * 
 * <p>Java class for JournalInfoTYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JournalInfoTYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FinancialYear" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="JournalId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="JournalEntryId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="JournalDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JournalInfoTYPE", propOrder = {
    "financialYear",
    "journalId",
    "journalEntryId",
    "journalDate"
})
public class JournalInfoTYPE {

    @XmlElement(name = "FinancialYear", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar financialYear;
    @XmlElement(name = "JournalId", required = true)
    protected String journalId;
    @XmlElement(name = "JournalEntryId", required = true)
    protected String journalEntryId;
    @XmlElement(name = "JournalDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar journalDate;

    /**
     * Gets the value of the financialYear property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFinancialYear() {
        return financialYear;
    }

    /**
     * Sets the value of the financialYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFinancialYear(XMLGregorianCalendar value) {
        this.financialYear = value;
    }

    /**
     * Gets the value of the journalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJournalId() {
        return journalId;
    }

    /**
     * Sets the value of the journalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJournalId(String value) {
        this.journalId = value;
    }

    /**
     * Gets the value of the journalEntryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJournalEntryId() {
        return journalEntryId;
    }

    /**
     * Sets the value of the journalEntryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJournalEntryId(String value) {
        this.journalEntryId = value;
    }

    /**
     * Gets the value of the journalDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getJournalDate() {
        return journalDate;
    }

    /**
     * Sets the value of the journalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setJournalDate(XMLGregorianCalendar value) {
        this.journalDate = value;
    }

}
