//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.12 at 10:02:46 PM CEST 
//


package se.sie.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Typdefinition för en angivelse av en dimension
 * 
 * <p>Java class for ObjectGroupReferenceTYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectGroupReferenceTYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TypeOfObjectGroupId" type="{}TypeOfObjectGroupIdTYPE"/>
 *         &lt;element name="ObjectGroupId" type="{}ObjectGroupIdTYPE"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectGroupReferenceTYPE", propOrder = {
    "typeOfObjectGroupId",
    "objectGroupId"
})
public class ObjectGroupReferenceTYPE {

    @XmlElement(name = "TypeOfObjectGroupId", required = true)
    protected String typeOfObjectGroupId;
    @XmlElement(name = "ObjectGroupId", required = true)
    protected String objectGroupId;

    /**
     * Gets the value of the typeOfObjectGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfObjectGroupId() {
        return typeOfObjectGroupId;
    }

    /**
     * Sets the value of the typeOfObjectGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfObjectGroupId(String value) {
        this.typeOfObjectGroupId = value;
    }

    /**
     * Gets the value of the objectGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectGroupId() {
        return objectGroupId;
    }

    /**
     * Sets the value of the objectGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectGroupId(String value) {
        this.objectGroupId = value;
    }

}
