//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.12 at 10:02:46 PM CEST 
//


package se.sie.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the se.sie.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.sie.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SIE }
     * 
     */
    public SIE createSIE() {
        return new SIE();
    }

    /**
     * Create an instance of {@link SIE.AccountsReceivable }
     * 
     */
    public SIE.AccountsReceivable createSIEAccountsReceivable() {
        return new SIE.AccountsReceivable();
    }

    /**
     * Create an instance of {@link SIE.AccountsReceivable.Invoices }
     * 
     */
    public SIE.AccountsReceivable.Invoices createSIEAccountsReceivableInvoices() {
        return new SIE.AccountsReceivable.Invoices();
    }

    /**
     * Create an instance of {@link SIE.AccountsReceivable.Customers }
     * 
     */
    public SIE.AccountsReceivable.Customers createSIEAccountsReceivableCustomers() {
        return new SIE.AccountsReceivable.Customers();
    }

    /**
     * Create an instance of {@link SIE.AccountsPayable }
     * 
     */
    public SIE.AccountsPayable createSIEAccountsPayable() {
        return new SIE.AccountsPayable();
    }

    /**
     * Create an instance of {@link SIE.AccountsPayable.Invoices }
     * 
     */
    public SIE.AccountsPayable.Invoices createSIEAccountsPayableInvoices() {
        return new SIE.AccountsPayable.Invoices();
    }

    /**
     * Create an instance of {@link SIE.AccountsPayable.Suppliers }
     * 
     */
    public SIE.AccountsPayable.Suppliers createSIEAccountsPayableSuppliers() {
        return new SIE.AccountsPayable.Suppliers();
    }

    /**
     * Create an instance of {@link SIE.Accounting }
     * 
     */
    public SIE.Accounting createSIEAccounting() {
        return new SIE.Accounting();
    }

    /**
     * Create an instance of {@link SIE.Accounting.FinancialYears }
     * 
     */
    public SIE.Accounting.FinancialYears createSIEAccountingFinancialYears() {
        return new SIE.Accounting.FinancialYears();
    }

    /**
     * Create an instance of {@link SIE.Accounting.FinancialYears.FinancialYear }
     * 
     */
    public SIE.Accounting.FinancialYears.FinancialYear createSIEAccountingFinancialYearsFinancialYear() {
        return new SIE.Accounting.FinancialYears.FinancialYear();
    }

    /**
     * Create an instance of {@link SIE.Accounting.FinancialYears.FinancialYear.ClosingBalances }
     * 
     */
    public SIE.Accounting.FinancialYears.FinancialYear.ClosingBalances createSIEAccountingFinancialYearsFinancialYearClosingBalances() {
        return new SIE.Accounting.FinancialYears.FinancialYear.ClosingBalances();
    }

    /**
     * Create an instance of {@link SIE.Accounting.FinancialYears.FinancialYear.Budgets }
     * 
     */
    public SIE.Accounting.FinancialYears.FinancialYear.Budgets createSIEAccountingFinancialYearsFinancialYearBudgets() {
        return new SIE.Accounting.FinancialYears.FinancialYear.Budgets();
    }

    /**
     * Create an instance of {@link SIE.Accounting.FinancialYears.FinancialYear.OpeningBalances }
     * 
     */
    public SIE.Accounting.FinancialYears.FinancialYear.OpeningBalances createSIEAccountingFinancialYearsFinancialYearOpeningBalances() {
        return new SIE.Accounting.FinancialYears.FinancialYear.OpeningBalances();
    }

    /**
     * Create an instance of {@link SIE.Accounting.FinancialYears.FinancialYear.Journals }
     * 
     */
    public SIE.Accounting.FinancialYears.FinancialYear.Journals createSIEAccountingFinancialYearsFinancialYearJournals() {
        return new SIE.Accounting.FinancialYears.FinancialYear.Journals();
    }

    /**
     * Create an instance of {@link SIE.Accounting.FinancialYears.FinancialYear.Journals.Journal }
     * 
     */
    public SIE.Accounting.FinancialYears.FinancialYear.Journals.Journal createSIEAccountingFinancialYearsFinancialYearJournalsJournal() {
        return new SIE.Accounting.FinancialYears.FinancialYear.Journals.Journal();
    }

    /**
     * Create an instance of {@link SIE.Accounting.FinancialYears.FinancialYear.Journals.Journal.JournalEntry }
     * 
     */
    public SIE.Accounting.FinancialYears.FinancialYear.Journals.Journal.JournalEntry createSIEAccountingFinancialYearsFinancialYearJournalsJournalJournalEntry() {
        return new SIE.Accounting.FinancialYears.FinancialYear.Journals.Journal.JournalEntry();
    }

    /**
     * Create an instance of {@link SIE.Accounting.Objects }
     * 
     */
    public SIE.Accounting.Objects createSIEAccountingObjects() {
        return new SIE.Accounting.Objects();
    }

    /**
     * Create an instance of {@link SIE.Accounting.TypeOfObjects }
     * 
     */
    public SIE.Accounting.TypeOfObjects createSIEAccountingTypeOfObjects() {
        return new SIE.Accounting.TypeOfObjects();
    }

    /**
     * Create an instance of {@link SIE.Accounting.ObjectGroups }
     * 
     */
    public SIE.Accounting.ObjectGroups createSIEAccountingObjectGroups() {
        return new SIE.Accounting.ObjectGroups();
    }

    /**
     * Create an instance of {@link SIE.Accounting.TypeOfObjectGroups }
     * 
     */
    public SIE.Accounting.TypeOfObjectGroups createSIEAccountingTypeOfObjectGroups() {
        return new SIE.Accounting.TypeOfObjectGroups();
    }

    /**
     * Create an instance of {@link SIE.Accounting.Accounts }
     * 
     */
    public SIE.Accounting.Accounts createSIEAccountingAccounts() {
        return new SIE.Accounting.Accounts();
    }

    /**
     * Create an instance of {@link SIE.Accounting.Accounts.Account }
     * 
     */
    public SIE.Accounting.Accounts.Account createSIEAccountingAccountsAccount() {
        return new SIE.Accounting.Accounts.Account();
    }

    /**
     * Create an instance of {@link SIE.FileInfo }
     * 
     */
    public SIE.FileInfo createSIEFileInfo() {
        return new SIE.FileInfo();
    }

    /**
     * Create an instance of {@link SIE.Company }
     * 
     */
    public SIE.Company createSIECompany() {
        return new SIE.Company();
    }

    /**
     * Create an instance of {@link BalanceWithPeriodTYPE }
     * 
     */
    public BalanceWithPeriodTYPE createBalanceWithPeriodTYPE() {
        return new BalanceWithPeriodTYPE();
    }

    /**
     * Create an instance of {@link ObjectGroupReferenceTYPE }
     * 
     */
    public ObjectGroupReferenceTYPE createObjectGroupReferenceTYPE() {
        return new ObjectGroupReferenceTYPE();
    }

    /**
     * Create an instance of {@link ObjectReferenceTYPE }
     * 
     */
    public ObjectReferenceTYPE createObjectReferenceTYPE() {
        return new ObjectReferenceTYPE();
    }

    /**
     * Create an instance of {@link PaymentTYPE }
     * 
     */
    public PaymentTYPE createPaymentTYPE() {
        return new PaymentTYPE();
    }

    /**
     * Create an instance of {@link LedgerEntryTYPE }
     * 
     */
    public LedgerEntryTYPE createLedgerEntryTYPE() {
        return new LedgerEntryTYPE();
    }

    /**
     * Create an instance of {@link JournalInfoTYPE }
     * 
     */
    public JournalInfoTYPE createJournalInfoTYPE() {
        return new JournalInfoTYPE();
    }

    /**
     * Create an instance of {@link SIE.AccountsReceivable.Invoices.Invoice }
     * 
     */
    public SIE.AccountsReceivable.Invoices.Invoice createSIEAccountsReceivableInvoicesInvoice() {
        return new SIE.AccountsReceivable.Invoices.Invoice();
    }

    /**
     * Create an instance of {@link SIE.AccountsReceivable.Customers.Customer }
     * 
     */
    public SIE.AccountsReceivable.Customers.Customer createSIEAccountsReceivableCustomersCustomer() {
        return new SIE.AccountsReceivable.Customers.Customer();
    }

    /**
     * Create an instance of {@link SIE.AccountsPayable.Invoices.Invoice }
     * 
     */
    public SIE.AccountsPayable.Invoices.Invoice createSIEAccountsPayableInvoicesInvoice() {
        return new SIE.AccountsPayable.Invoices.Invoice();
    }

    /**
     * Create an instance of {@link SIE.AccountsPayable.Suppliers.Supplier }
     * 
     */
    public SIE.AccountsPayable.Suppliers.Supplier createSIEAccountsPayableSuppliersSupplier() {
        return new SIE.AccountsPayable.Suppliers.Supplier();
    }

    /**
     * Create an instance of {@link SIE.Accounting.FinancialYears.FinancialYear.Balances }
     * 
     */
    public SIE.Accounting.FinancialYears.FinancialYear.Balances createSIEAccountingFinancialYearsFinancialYearBalances() {
        return new SIE.Accounting.FinancialYears.FinancialYear.Balances();
    }

    /**
     * Create an instance of {@link SIE.Accounting.FinancialYears.FinancialYear.ClosingBalances.ClosingBalance }
     * 
     */
    public SIE.Accounting.FinancialYears.FinancialYear.ClosingBalances.ClosingBalance createSIEAccountingFinancialYearsFinancialYearClosingBalancesClosingBalance() {
        return new SIE.Accounting.FinancialYears.FinancialYear.ClosingBalances.ClosingBalance();
    }

    /**
     * Create an instance of {@link SIE.Accounting.FinancialYears.FinancialYear.Budgets.Budget }
     * 
     */
    public SIE.Accounting.FinancialYears.FinancialYear.Budgets.Budget createSIEAccountingFinancialYearsFinancialYearBudgetsBudget() {
        return new SIE.Accounting.FinancialYears.FinancialYear.Budgets.Budget();
    }

    /**
     * Create an instance of {@link SIE.Accounting.FinancialYears.FinancialYear.OpeningBalances.OpeningBalance }
     * 
     */
    public SIE.Accounting.FinancialYears.FinancialYear.OpeningBalances.OpeningBalance createSIEAccountingFinancialYearsFinancialYearOpeningBalancesOpeningBalance() {
        return new SIE.Accounting.FinancialYears.FinancialYear.OpeningBalances.OpeningBalance();
    }

    /**
     * Create an instance of {@link SIE.Accounting.FinancialYears.FinancialYear.Journals.Journal.JournalEntry.LedgerEntry }
     * 
     */
    public SIE.Accounting.FinancialYears.FinancialYear.Journals.Journal.JournalEntry.LedgerEntry createSIEAccountingFinancialYearsFinancialYearJournalsJournalJournalEntryLedgerEntry() {
        return new SIE.Accounting.FinancialYears.FinancialYear.Journals.Journal.JournalEntry.LedgerEntry();
    }

    /**
     * Create an instance of {@link SIE.Accounting.Objects.Object }
     * 
     */
    public SIE.Accounting.Objects.Object createSIEAccountingObjectsObject() {
        return new SIE.Accounting.Objects.Object();
    }

    /**
     * Create an instance of {@link SIE.Accounting.TypeOfObjects.TypeOfObject }
     * 
     */
    public SIE.Accounting.TypeOfObjects.TypeOfObject createSIEAccountingTypeOfObjectsTypeOfObject() {
        return new SIE.Accounting.TypeOfObjects.TypeOfObject();
    }

    /**
     * Create an instance of {@link SIE.Accounting.ObjectGroups.ObjectGroup }
     * 
     */
    public SIE.Accounting.ObjectGroups.ObjectGroup createSIEAccountingObjectGroupsObjectGroup() {
        return new SIE.Accounting.ObjectGroups.ObjectGroup();
    }

    /**
     * Create an instance of {@link SIE.Accounting.TypeOfObjectGroups.TypeOfObjectGroup }
     * 
     */
    public SIE.Accounting.TypeOfObjectGroups.TypeOfObjectGroup createSIEAccountingTypeOfObjectGroupsTypeOfObjectGroup() {
        return new SIE.Accounting.TypeOfObjectGroups.TypeOfObjectGroup();
    }

    /**
     * Create an instance of {@link SIE.Accounting.Accounts.Account.SruCode }
     * 
     */
    public SIE.Accounting.Accounts.Account.SruCode createSIEAccountingAccountsAccountSruCode() {
        return new SIE.Accounting.Accounts.Account.SruCode();
    }

}
